CREATE DATABASE mixonat;

CREATE USER mixo WITH PASSWORD 'mixo';
GRANT ALL PRIVILEGES ON DATABASE Mixonat TO mixo;

CREATE TABLE IF NOT EXISTS sdf (
	id SERIAL PRIMARY KEY,
	name TEXT,
	sdf_file TEXT); 
